Update byron_release2.yml

diff --git a/.github/workflows/byron_release2.yml b/.github/workflows/byron_release2.yml
--- a/.github/workflows/byron_release2.yml
+++ b/.github/workflows/byron_release2.yml
@@ -55,6 +55,13 @@ jobs:
           echo "job_id"
           echo $job_id
 
+          if ($job_id -eq "")
+          {
+             echo "Exiting because unable to retrieve job ID
+             exit 1
+          }
+
+
           
           
           
